### ISSUE TITLE
Fail gracefully, if connection to seq fails

### ISSUE THREAD

**Issue by balazsorban44** [datalust/pino-seq#14]
Hi!

We use `pino-seq` together with `pino` in our Next.js app to log errors to Seq. Today, an error occurred in our Seq server, which made the connection between our app and Seq fail with the following error:

```
2020-11-19T07:41:47.743700409Z events.js:306 2020-11-19T07:41:47.743785314Z throw err;
// Unhandled 'error' event 2020-11-19T07:41:47.743803315Z ^ 2020-11-19T07:41:47.743807616Z
2020-11-19T07:41:47.743811616Z Error [ERR_UNHANDLED_ERROR]: Unhandled error.
('HTTP log shipping failed: 502') 2020-11-19T07:41:47.743815916Z at PinoSeqStream.emit (events.js:304:17)
2020-11-19T07:41:47.743819816Z at emitErrorNT (internal/streams/destroy.js:92:8) 
2020-11-19T07:41:47.743823717Z at emitErrorAndCloseNT (internal/streams/destroy.js:60:3) 
2020-11-19T07:41:47.743827917Z at processTicksAndRejections (internal/process/task_queues.js:84:21) 
{
 2020-11-19T07:41:47.743831817Z code: 'ERR_UNHANDLED_ERROR',
2020-11-19T07:41:47.743835517Z context: 'HTTP log shipping failed: 502' 2020-11-19T07:41:47.743839318Z } 2020-11-19T07:41:47.763250218Z error Command failed with exit code 1.
2020-11-19T07:41:47.763348224Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This crashed our whole Next.js app.

After some digging, I see that the `onError` method will always call `this.destroy`, implemented here:
https://github.com/datalust/pino-seq/blob/8971831caa468ff4ead5ff75cfcd36de1ebfdb7b/pinoSeqStream.js#L22

So users cannot remove this. I was wondering if it was a deliberate choice, and if so, what is the explanation? Would it be possible to make the `onError` totally overrideable such that connection errors to `Seq` will not crash our entire app?

My current solution was to override the destroy method of the stream like so:

```js
  const stream = pinoToSeq.createStream({
    apiKey: process.env.SEQ_API_KEY,
    serverUrl: process.env.SEQ_SERVER_URL,
  })

  /**
   * HACK: https://nodejs.org/api/stream.html#stream_writable_destroy_error
   * should not be overriden, but pino-seq wants to destroy if connection to seq fails.
   */
  stream.destroy = console.error

```

but the [Node.js docs](https://nodejs.org/api/stream.html#stream_writable_destroy_error) tells me I should not do that.

**Comment by larenelg** [comment]
Hi @balazsorban44, thanks so much for your PR, I've tested and have left a comment!

**Comment by balazsorban44** [comment]
Using Node 12 here.
